name: Tag a DART version
description: Push a Git tag.
author: Two Six Tech DART Team
inputs:
  token:
    required: true
    description: Github Token for pushing to the repository
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.token }}
branding:
  icon: search
  color: yellow