name: Publish Tag

on: push

jobs:
  tag-release:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          persist-credentials: false
      - name: Tag a release
        uses: ./
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  test-tag-release-sbt:
    if: github.ref == 'refs/heads/DART-1314-adding-github-actions'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          persist-credentials: false
      - name: Tag a release
        uses: ./
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          audit: "yes"

  test-tag-release-app:
    if: github.ref == 'refs/heads/DART-1314-adding-github-actions'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          persist-credentials: false
      - name: Tag a release
        uses: ./
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          audit: "yes"
          release_version: ${{ format('2.0.{0}', env.GITHUB_RUN_NUMBER) }}

  test-tag:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
        - run: echo "Executed on Tag"